We received a request to register a new account on $site$ with your email address under the name "$userName$".  If you submitted this request, please confirm your registration by copying the confirmation code into the blank on the confirmation page or by visiting the location below.

The confirmation code is:   $confirmCode$

The web address to confirm directly is:

  $confirmURL$

If you didn't attempt to create an account, please excuse the interruption.

Sincerely,
$site$ Administrator$\n$

